CREATE TABLE IF NOT EXISTS polls (
    title VARCHAR(1100) NOT NULL,
    creator VARCHAR(20) NOT NULL,
    guild VARCHAR(20) NOT NULL,
    closed BOOLEAN DEFAULT FALSE,
    id UUID NOT NULL UNIQUE PRIMARY KEY,
    options TEXT[] NOT NULL,
    FOREIGN KEY (guild) REFERENCES guilds(id) ON DELETE CASCADE
);
